//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.CNN {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.CNN.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import numpy as np
        ///import pandas as pd
        ///from sklearn.model_selection import train_test_split
        ///
        ///def get_data(file):
        ///
        ///    data = pd.read_csv(file).sample(n=10000)
        ///    #print(data.head)
        ///
        ///    feat_raw = data[&apos;quizzes&apos;]
        ///    label_raw = data[&apos;solutions&apos;]
        ///
        ///    feat = []
        ///    label = []
        ///
        ///    for i in feat_raw:
        ///
        ///        x = np.array([int(j) for j in i]).reshape((9,9,1))
        ///        feat.append(x)
        ///
        ///    feat = np.array(feat)
        ///    feat = feat/9
        ///    feat -= .5
        ///
        ///    for i in label_raw:
        ///
        ///        x = np.a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data_processes {
            get {
                return ResourceManager.GetString("data_processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # may require update keras
        ///#!pip install keras --upgrade
        ///import os
        ///
        ///import numpy as np
        ///from keras import models, utils
        ///import pandas as pd
        ///from huggingface_hub import hf_hub_download
        ///from tensorflow import keras
        ///import tensorflow as tf
        ///from tensorflow.python.keras import layers
        ///from tensorflow.python.keras.models import Sequential
        ///
        ///class SudokuSolver:
        ///    def __init__(self, model_path):
        ///        self.model = self.load_model(model_path)
        ///
        ///    def load_model(self, model_path):
        ///        return m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FNN {
            get {
                return ResourceManager.GetString("FNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from keras import Input, Model, Sequential
        ///from keras.layers import Add, Conv2D, MaxPooling2D, Concatenate, Activation, Dropout, Flatten, Dense, Reshape, BatchNormalization
        ///
        ///
        ///def get_model():
        ///
        ///    model = keras.models.Sequential()
        ///
        ///    model.add(Conv2D(64, kernel_size=(3,3), activation=&apos;relu&apos;, padding=&apos;same&apos;, input_shape=(9,9,1)))
        ///    model.add(BatchNormalization())
        ///    model.add(Conv2D(64, kernel_size=(3,3), activation=&apos;relu&apos;, padding=&apos;same&apos;))
        ///    model.add(BatchNormalization())
        ///    model.add(C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quizzes,solutions
        ///004300209005009001070060043006002087190007400050083000600000105003508690042910300,864371259325849761971265843436192587198657432257483916689734125713528694542916378
        ///040100050107003960520008000000000017000906800803050620090060543600080700250097100,346179258187523964529648371965832417472916835813754629798261543631485792254397186
        ///600120384008459072000006005000264030070080006940003000310000050089700000502000190,695127384138459672724836915851264739273981546946573821317692458489715263562348197
        ///49 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sudoku {
            get {
                return ResourceManager.GetString("sudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import copy
        ///import keras
        ///import numpy as np
        ///import clr 
        ///clr.AddReference(&apos;Sudoku.CNN&apos;)
        ///from Sudoku.CNN import CNNSolver
        ///
        ///
        ///def norm(a):
        ///    return (a/9)-.5
        ///
        ///
        ///
        ///def denorm(a):
        ///    return (a+.5)*9
        ///
        ///
        ///def inference_sudoku(sample):
        ///
        ///    &apos;&apos;&apos;
        ///        This function solve the sudoku by filling blank positions one by one.
        ///    &apos;&apos;&apos;
        ///
        ///    feat = copy.copy(sample)
        ///
        ///    while(1):
        ///
        ///        out = model.predict(feat.reshape((1,9,9,1)))
        ///        out = out.squeeze()
        ///
        ///        pred = np.argmax(out, axis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sudoku_py {
            get {
                return ResourceManager.GetString("Sudoku.py", resourceCulture);
            }
        }
    }
}
